name: Build Mac

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-14-arm64
    steps:
      - uses: actions/checkout@v3

      - name: Setup python link
        run: |
          mkdir -p $HOME/.local/bin
          ln -sf $(which python3) $HOME/.local/bin/python
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: npm install

      - name: Build dist
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
