name: Build Mac

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-14-arm64
    steps:
      - uses: actions/checkout@v3

      - name: Setup python link
        run: |
          mkdir -p $HOME/.local/bin
          ln -sf $(which python3) $HOME/.local/bin/python
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: npm install

      - name: Build dist
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dorico-fixer-mac
          path: dist/*.dmg

      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
