name: Build Mac

on:
  push:
    tags:
      - "v*

      
jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.12.2"

      - name: Setup Python (for legacy tools)
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Configure Python symlink for legacy scripts
        run: |
          PYTHON_PATH="$(which python3)"
          if ! [ -x "/usr/bin/python" ]; then
            echo "Creating python symlink from $PYTHON_PATH"
            sudo ln -s "$PYTHON_PATH" /usr/bin/python || echo "Symlink skipped: insufficient permissions"
          fi

      - name: Install dependencies
        run: npm install

      - name: Fix vulnerabilities (optional but recommended)
        run: npm audit fix --force

      - name: Build macOS distributable
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PYTHON: python3

      - name: Upload .dmg artifact
        uses: actions/upload-artifact@v4
        with:
          name: dorico-fixer-mac
          path: dist/*.dmg

      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
