name: Build Mac

on:
  push:
    branches:
      - main

jobs:
  build-mac:
    runs-on: macos-latest

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Fix python path (create symlink for python2)
        run: |
          if ! [ -e /usr/bin/python ]; then
            sudo ln -s $(which python3) /usr/bin/python
          fi

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run dist

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mac-build
          path: dist/
